# Generated by Django 5.1.4 on 2024-12-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasmlar',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
